name: Update Data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 1 * * *" # every day at 1am UTC

env:
  STATE: wy # <-- update this value per state repo, e.g. il, tx, ny, etc.

jobs:
  update-data:
    name: Update Data
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: windy-civi/opencivicdata-blockchain-transformer@main
        with:
           state: ${{ env.STATE }}
           input-folder: ${{ runner.temp }}/_working/_data/${{ env.STATE }}
           allow-session-fix: true

      # - name: Update Repo
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config user.email "no_email"
      #     git config user.name "Windy Civi Bot"
      #     git fetch origin main
      #     git pull origin main --rebase || true

      #     git add data_output bill_session_mapping sessions
      #     git diff --cached --quiet && echo "No changes to commit" || git commit -m "Automated report update (report dated ${{ steps.get-date.outputs.date }})"
      #     git push || echo "⚠️ Git push failed — possibly due to upstream changes."
